language: go
sudo: required
go:
  - 1.6
services:
  - docker

notifications:
  slack:
    secure: BOWbEtnhETJcg03+wNPAoUxp73e5qBG1Len/qYX/SoR/3A7MSnBJw9Zs7wGiSzKVU75I+hQnjKanbeYVZ26+O+LXhDYNIuossnsE+QG4EpWuWfLR+QKXOvhVm+wMazkTVC0q3qk0TCF/BT/R780wrTQFUKCeEe2UVGF7XCjxIiMpnSxKeBIkNXFOV/MoBkDCKRradHwpL7MroC1ncT0C+JZlXzvupjvccvJIISFHOiU+je5P7UWy1+yo6vBV/y7rZBO4gkpm5plOnRt+7QQzV0x05gBHbxARzUpCgyNd1S864a7Q8Snt4WECvbhtj7MvVzuuZhbrdGldNdVm+piFOgt/Oz/7WOv8AUWOPssfRjMl0vUdmAGjMvOfIl8o8CmI4u1jNR0X5Yu7I5zltDGnLBQbcCKLeJaBWbHuF/8CYWrHQf+Kw1CcP+IW6cWeglBNO63SLEwjRk7WC+NRnZp+irOdlmAylDBvRqQvLHQ0Mz2c023PWEF7FsFRM6f0Fvch4BUePdIMzNNQKNk2ddI2Pn32bVole4/4xK51DRRWXocII4X0KHWFjZfc0Zpo/ArzjDgsbT+M0faKgPK9NgRFD/1FRAsNrzIyq4DO/Em6mPPNkcUngdwOdi3onGQRWNAxOR/c6pjORGmWEA1ZlUeYsvZLnVLwLJpXlxYCTkHurMY=

cache:
  directories:
  - vendor
  - $HOME/gopath/pkg

before_install:
  - export MASTER_BRANCH=origin/master
  - git fetch --depth=50 origin master:remotes/origin/master

install:
  - if git log -1 | grep "\[ci cover\]"; then
      go get github.com/mattn/goveralls;
      go get golang.org/x/tools/cmd/cover;
      go get github.com/modocache/gover;
    fi
  - if make has-tags; then
      sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D;
      sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list';
      sudo apt-get update;
      sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.11.2-0~trusty;
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    fi
  - if [ -n "${TRAVIS_TAG}" ]; then
      go get github.com/aktau/github-release;
    fi

script:
  - set -eo pipefail
  - make info
  - make bootstrap
  - if [ "${TRAVIS_SECURE_ENV_VARS}" == "false" ]; then
      make test;
      exit 0;
    fi
  - if git log -1 | grep "\[ci cover\]"; then
      make test-with-coverage;
      goveralls -coverprofile=gover.coverprofile -service=travis-ci;
    else
      make test;
    fi

after_success:
  - if make has-tags; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      make docker-build;
      make docker-push;
      curl -X POST "${MICROBADGER_URL}";
    fi
  - if [ -n "${TRAVIS_TAG}" ]; then
      make github-release;
    fi

