language: go
sudo: required
go:
  - 1.6
services:
  - docker

notifications:
  slack:
    secure: 2MPp8QORwHUGHDrpbdQ4+f4flNkrcjjFYu4W5Pkx2qA+NXyJyPLnY37lX48i9eav2viuo62myBABVBoR5zgTpL3FjsXWtsil135gvNvkPI8iO7fbcal3sJYeuj2kNgM6jkH893FwJodublskVIlVCDoz318djqI+fYaGl4ke+8rU1cjjlujapJIk/MT34vBvQmAd/oA4fRYBVo00AAgm9PCNH+T0ma7rn63Bta4jaVymx9Ty0VF7dl850WZJfsL5RPKLRYagT3AiHrSR+umw3DDA9RDulNnCn28TMgwAbMb0/q4eztci78gaL16KFPjNR388EZViCFWf30GTyWnr+SJqLYTJJ4VdlULtvtzWKpFTLAxw1ZieOVmtmR7x80jiHW63mbEz4wqvoL/XbT0u2FyxUTjnZ9/XWxJ/EgfJHoHIdbSeMEp7HReh5MBOr6TY+Lc+F6ZHxxR5yCNl3KERL2vWQkpkOrt3X0elFMCGlxn9l+QNI525q454HA2hqCncwFy7flhddThyw2NupiYWzxIehKHGPTWfMRv3oJTg8QO2j3aeP/nab9Hwdf6gYJYfI1GOP/rU/fFlWoxIHgcfFxuBeVYP4Q0R5PETgvoGP076VAXnzcJBrE3j1h+EPmXqqTZy0pz4QNFUa1ckwwy1r+ewXa7npaaV/9aYEsnkVMo=

cache:
  directories:
  - vendor
  - $HOME/gopath/pkg

before_install:
  - export MASTER_BRANCH=origin/master
  - git fetch --depth=50 origin master:remotes/origin/master

install:
  - if git log -1 | grep "\[ci cover\]"; then
      go get github.com/mattn/goveralls;
      go get golang.org/x/tools/cmd/cover;
      go get github.com/modocache/gover;
    fi
  - if make has-tags; then
      sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D;
      sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list';
      sudo apt-get update;
      sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.11.2-0~trusty;
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    fi
  - if [ -n "${TRAVIS_TAG}" ]; then
      go get github.com/aktau/github-release;
    fi

script:
  - set -eo pipefail
  - make info
  - make bootstrap
  - if [ "${TRAVIS_SECURE_ENV_VARS}" == "false" ]; then
      make test;
      exit 0;
    fi
  - if git log -1 | grep "\[ci cover\]"; then
      make test-with-coverage;
      goveralls -coverprofile=gover.coverprofile -service=travis-ci;
    else
      make test;
    fi

after_success:
  - if make has-tags; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      make docker-build;
      make docker-push;
      curl -X POST "${MICROBADGER_URL}";
    fi
  - if [ -n "${TRAVIS_TAG}" ]; then
      make github-release;
    fi

